spring:
  application:
    name: studyjpa
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:./data/jpa;Mode=Oracle;AUTO_SERVER=TRUE"
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

server:
  port: 7071




